---
- name: Auto Heal - Reiniciar serviço apenas se estiver falhando
  hosts: servidores
  become: yes
  gather_facts: no

  vars:
    service_name: nginx  # altere aqui para o serviço desejado

  tasks:

    - name: Coletar status do serviço
      ansible.builtin.command: systemctl show {{ service_name }} --no-page
      register: service_raw
      changed_when: false
      failed_when: false

    - name: Extrair ActiveState
      set_fact:
        active_state: "{{ service_raw.stdout | regex_search('ActiveState=(.*)', '\\1') | first }}"

    - name: Extrair SubState
      set_fact:
        sub_state: "{{ service_raw.stdout | regex_search('SubState=(.*)', '\\1') | first }}"

    - name: Exibir status atual
      debug:
        msg: "Serviço {{ service_name }} está em ActiveState={{ active_state }} SubState={{ sub_state }}"

    - name: Reiniciar serviço se estiver falhando
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
      when: active_state != "active"

    - name: Confirmar novo status após restart
      ansible.builtin.systemd:
        name: "{{ service_name }}"
      register: new_status
      when: active_state != "active"

    - name: Exibir novo status
      debug:
        msg: "Novo estado: {{ new_status.status.ActiveState }}"
      when: active_state != "active"
